import numpy as np
import torch
from numpy.lib.format import open_memmap
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

from loganalyzer.data import read_log_file

def _detect_device() -> str:
    device = "cpu"
    if torch.cuda.is_available():
        device = "cuda"
    print(f"Using {device.upper()}")
    return device

def generate_embeddings(
    input_file: str,
    batch_size: int = 500,
) -> tuple[int, int]:
    """
    Generate embeddings for each line and save to a .npy file using memmap.

    Uses sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 (384-dim,
    multilingual, fast). Writes directly to disk via numpy memmap — only the
    current batch is kept in RAM, so memory usage stays low even for large files.

    Args:
        input_file: Path to the log file.
        batch_size: Number of lines processed per batch.

    Returns:
        A tuple of (number_of_embeddings, embedding_dimension).
    """
    lines = read_log_file(input_file)
    output_file = input_file + ".embeddings.npy"
    device = _detect_device()
    model = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        device=device,
    )

    for i in tqdm(range(0, len(lines), batch_size), desc="Generating embeddings"):
        batch = lines[i:i + batch_size]
        batch_embeddings = model.encode(
            batch,
            batch_size=batch_size,
            show_progress_bar=False,
            convert_to_numpy=True,
        )
        if i == 0:
            dim = batch_embeddings.shape[1]
            mmap = open_memmap(output_file, dtype="float32", mode="w+", shape=(len(lines), dim))

        mmap[i:i + len(batch)] = batch_embeddings

    mmap.flush()
    print("\n ********************* Embeddings Generation Complete *********************")
    print(f"Saved {len(lines)} embeddings of dimension {dim} to {output_file}")

    return len(lines), dim


def load_embeddings(file_path: str) -> np.ndarray:
    """Load embeddings from a .npy file using memory-mapped I/O.

    Args:
        file_path: Path to the .npy file generated by generate_embeddings.

    Returns:
        A numpy array with shape (N, 384) backed by memory-mapped I/O —
        suitable for large files without loading them entirely into RAM.
    """
    return np.load(file_path, mmap_mode="r")